services:
  - type: web
    name: sleep-detector-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.detector.app:app --host 0.0.0.0 --port 10000
    plan: free